#ifndef ENGINE_HPP
#define ENGINE_HPP

#include <stdlib.h>
#include <time.h>

#include <fstream>
#include <iostream>
#include <sstream>
#include <string>

#include "FileManager.hpp"
#include "ResourceManager.hpp"
#include "SceneManager.hpp"
#include "imgui.h"
#include "imgui_impl_sdl2.h"
#include "imgui_impl_sdlrenderer.h"

/**
 * This class sets up the main game engine
 */
class Engine {
   public:
    /**
     * Constructor of Engine
     */
    Engine();
    /**
     * Destructor
     */
    ~Engine();
    /**
     * Manages the input generated by the user and sends it to the required game object or manager
     */
    void Input(bool* quit);
    /**
     * Updates state of all aspects of the game engine each frame
     */
    void Update();
    /**
     * Renders all renderable aspects of the game engine to include the toolbars and game scene
     */
    void Render(ImGuiIO& mIo);
    /**
     * Main Game Loop that runs forever
     */
    void MainGameLoop();
    /**
     * Initialization and shutdown pattern
     * Explicitly call 'Start' to launch the engine
     */
    void Start();
    /**
     * Starts all required game engine actions to successfully run the game loop
     */
    void Shutdown();

    /**
     * Request to startup the Graphics Subsystem
     */
    int InitializeGraphicsSubSystem();

    /**
     * Request to startup the Resource Manager and load all images in directory
     */
    void InitializeResourceSubSystem();

    /**
     * Request to startup the Scene Manager and set scene renderer
     */
    void InitializeSceneManagerSubSystem();

    /**
     * Request to startup the File Manager
     */
    void InitializeFileManagerSubSystem();

   private:
    void AddToGameFiles(std::string filename);
    // Engine Subsystem
    // Setup the Graphics Rendering Engine
    SDL_Window* mWindow;
    SDL_Renderer* mRenderer;
    SDL_Texture* mScreenTexture;
    ImVec2 mScreenEditorPos;
    std::string mCurrentLevelName = "Empty Level Template";
    std::vector<std::string> mLevelNames;
};

#endif
